spring:
  application:
    name: pidel
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pidel
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: 98123dsajjhasdjASDAsadasklgmALMNVPOIHGUlkjasdjlkj4lkj123lkjlkOIKLKPO777983123ssgayp
  lifetime: 90m

file:
  image.pizza.path: /pidel/resources/images

http:
  url: http://localhost:8080/api/v1